// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: payment.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Coordinates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinates) Reset() {
	*x = Coordinates{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinates) ProtoMessage() {}

func (x *Coordinates) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinates.ProtoReflect.Descriptor instead.
func (*Coordinates) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Coordinates) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Coordinates) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type PaymentError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StripeCode    string                 `protobuf:"bytes,3,opt,name=stripe_code,json=stripeCode,proto3" json:"stripe_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentError) Reset() {
	*x = PaymentError{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentError) ProtoMessage() {}

func (x *PaymentError) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentError.ProtoReflect.Descriptor instead.
func (*PaymentError) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PaymentError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PaymentError) GetStripeCode() string {
	if x != nil {
		return x.StripeCode
	}
	return ""
}

type CreateCheckOutSessionRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RiderId              string                 `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	RiderName            string                 `protobuf:"bytes,9,opt,name=rider_name,json=riderName,proto3" json:"rider_name,omitempty"`
	RiderAge             int32                  `protobuf:"varint,10,opt,name=rider_age,json=riderAge,proto3" json:"rider_age,omitempty"`
	Gender               string                 `protobuf:"bytes,11,opt,name=gender,proto3" json:"gender,omitempty"`
	PickupLocation       string                 `protobuf:"bytes,3,opt,name=pickup_location,json=pickupLocation,proto3" json:"pickup_location,omitempty"`
	DropoffLocation      string                 `protobuf:"bytes,4,opt,name=dropoff_location,json=dropoffLocation,proto3" json:"dropoff_location,omitempty"`
	EstimatedPrice       float32                `protobuf:"fixed32,2,opt,name=estimated_price,json=estimatedPrice,proto3" json:"estimated_price,omitempty"`
	EstimatedDistanceKm  float32                `protobuf:"fixed32,5,opt,name=estimated_distance_km,json=estimatedDistanceKm,proto3" json:"estimated_distance_km,omitempty"`
	EstimatedDurationMin int64                  `protobuf:"varint,6,opt,name=estimated_duration_min,json=estimatedDurationMin,proto3" json:"estimated_duration_min,omitempty"`
	DropoffCoordsLatLng  *Coordinates           `protobuf:"bytes,7,opt,name=dropoff_coords_lat_lng,json=dropoffCoordsLatLng,proto3" json:"dropoff_coords_lat_lng,omitempty"`
	PickupCoordsLatLng   *Coordinates           `protobuf:"bytes,8,opt,name=pickup_coords_lat_lng,json=pickupCoordsLatLng,proto3" json:"pickup_coords_lat_lng,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateCheckOutSessionRequest) Reset() {
	*x = CreateCheckOutSessionRequest{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCheckOutSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckOutSessionRequest) ProtoMessage() {}

func (x *CreateCheckOutSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckOutSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateCheckOutSessionRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCheckOutSessionRequest) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *CreateCheckOutSessionRequest) GetRiderName() string {
	if x != nil {
		return x.RiderName
	}
	return ""
}

func (x *CreateCheckOutSessionRequest) GetRiderAge() int32 {
	if x != nil {
		return x.RiderAge
	}
	return 0
}

func (x *CreateCheckOutSessionRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CreateCheckOutSessionRequest) GetPickupLocation() string {
	if x != nil {
		return x.PickupLocation
	}
	return ""
}

func (x *CreateCheckOutSessionRequest) GetDropoffLocation() string {
	if x != nil {
		return x.DropoffLocation
	}
	return ""
}

func (x *CreateCheckOutSessionRequest) GetEstimatedPrice() float32 {
	if x != nil {
		return x.EstimatedPrice
	}
	return 0
}

func (x *CreateCheckOutSessionRequest) GetEstimatedDistanceKm() float32 {
	if x != nil {
		return x.EstimatedDistanceKm
	}
	return 0
}

func (x *CreateCheckOutSessionRequest) GetEstimatedDurationMin() int64 {
	if x != nil {
		return x.EstimatedDurationMin
	}
	return 0
}

func (x *CreateCheckOutSessionRequest) GetDropoffCoordsLatLng() *Coordinates {
	if x != nil {
		return x.DropoffCoordsLatLng
	}
	return nil
}

func (x *CreateCheckOutSessionRequest) GetPickupCoordsLatLng() *Coordinates {
	if x != nil {
		return x.PickupCoordsLatLng
	}
	return nil
}

type CreateCheckOutSessionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	CheckoutUrl     string                 `protobuf:"bytes,2,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	SessionId       string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PaymentIntentId string                 `protobuf:"bytes,4,opt,name=payment_intent_id,json=paymentIntentId,proto3" json:"payment_intent_id,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Error           *PaymentError          `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateCheckOutSessionResponse) Reset() {
	*x = CreateCheckOutSessionResponse{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCheckOutSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckOutSessionResponse) ProtoMessage() {}

func (x *CreateCheckOutSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckOutSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateCheckOutSessionResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCheckOutSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateCheckOutSessionResponse) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

func (x *CreateCheckOutSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateCheckOutSessionResponse) GetPaymentIntentId() string {
	if x != nil {
		return x.PaymentIntentId
	}
	return ""
}

func (x *CreateCheckOutSessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateCheckOutSessionResponse) GetError() *PaymentError {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\apayment\"1\n" +
	"\vCoordinates\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\"]\n" +
	"\fPaymentError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vstripe_code\x18\x03 \x01(\tR\n" +
	"stripeCode\"\x88\x04\n" +
	"\x1cCreateCheckOutSessionRequest\x12\x19\n" +
	"\brider_id\x18\x01 \x01(\tR\ariderId\x12\x1d\n" +
	"\n" +
	"rider_name\x18\t \x01(\tR\triderName\x12\x1b\n" +
	"\trider_age\x18\n" +
	" \x01(\x05R\briderAge\x12\x16\n" +
	"\x06gender\x18\v \x01(\tR\x06gender\x12'\n" +
	"\x0fpickup_location\x18\x03 \x01(\tR\x0epickupLocation\x12)\n" +
	"\x10dropoff_location\x18\x04 \x01(\tR\x0fdropoffLocation\x12'\n" +
	"\x0festimated_price\x18\x02 \x01(\x02R\x0eestimatedPrice\x122\n" +
	"\x15estimated_distance_km\x18\x05 \x01(\x02R\x13estimatedDistanceKm\x124\n" +
	"\x16estimated_duration_min\x18\x06 \x01(\x03R\x14estimatedDurationMin\x12I\n" +
	"\x16dropoff_coords_lat_lng\x18\a \x01(\v2\x14.payment.CoordinatesR\x13dropoffCoordsLatLng\x12G\n" +
	"\x15pickup_coords_lat_lng\x18\b \x01(\v2\x14.payment.CoordinatesR\x12pickupCoordsLatLng\"\xec\x01\n" +
	"\x1dCreateCheckOutSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fcheckout_url\x18\x02 \x01(\tR\vcheckoutUrl\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12*\n" +
	"\x11payment_intent_id\x18\x04 \x01(\tR\x0fpaymentIntentId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12+\n" +
	"\x05error\x18\x06 \x01(\v2\x15.payment.PaymentErrorR\x05error2x\n" +
	"\x0ePaymentService\x12f\n" +
	"\x15CreateCheckOutSession\x12%.payment.CreateCheckOutSessionRequest\x1a&.payment.CreateCheckOutSessionResponseB\tZ\a.;protob\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_payment_proto_goTypes = []any{
	(*Coordinates)(nil),                   // 0: payment.Coordinates
	(*PaymentError)(nil),                  // 1: payment.PaymentError
	(*CreateCheckOutSessionRequest)(nil),  // 2: payment.CreateCheckOutSessionRequest
	(*CreateCheckOutSessionResponse)(nil), // 3: payment.CreateCheckOutSessionResponse
}
var file_payment_proto_depIdxs = []int32{
	0, // 0: payment.CreateCheckOutSessionRequest.dropoff_coords_lat_lng:type_name -> payment.Coordinates
	0, // 1: payment.CreateCheckOutSessionRequest.pickup_coords_lat_lng:type_name -> payment.Coordinates
	1, // 2: payment.CreateCheckOutSessionResponse.error:type_name -> payment.PaymentError
	2, // 3: payment.PaymentService.CreateCheckOutSession:input_type -> payment.CreateCheckOutSessionRequest
	3, // 4: payment.PaymentService.CreateCheckOutSession:output_type -> payment.CreateCheckOutSessionResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
