// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/rider_auth.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_rider_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rider_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_rider_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	BirthMonth    string                 `protobuf:"bytes,5,opt,name=birth_month,json=birthMonth,proto3" json:"birth_month,omitempty"`
	BirthYear     int64                  `protobuf:"varint,6,opt,name=birth_year,json=birthYear,proto3" json:"birth_year,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Id            string                 `protobuf:"bytes,9,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_rider_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rider_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_rider_auth_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *User) GetBirthMonth() string {
	if x != nil {
		return x.BirthMonth
	}
	return ""
}

func (x *User) GetBirthYear() int64 {
	if x != nil {
		return x.BirthYear
	}
	return 0
}

func (x *User) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *User) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status        int64                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Token         *Tokens                `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_proto_rider_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rider_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_rider_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuthResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AuthResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AuthResponse) GetToken() *Tokens {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *AuthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_rider_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rider_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_rider_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status        int64                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Token         *Tokens                `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_rider_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rider_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_rider_auth_proto_rawDescGZIP(), []int{4}
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LoginResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LoginResponse) GetToken() *Tokens {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *LoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetRiderDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRiderDetailsRequest) Reset() {
	*x = GetRiderDetailsRequest{}
	mi := &file_proto_rider_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRiderDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRiderDetailsRequest) ProtoMessage() {}

func (x *GetRiderDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rider_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRiderDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetRiderDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_rider_auth_proto_rawDescGZIP(), []int{5}
}

func (x *GetRiderDetailsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRiderDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status        int64                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRiderDetailsResponse) Reset() {
	*x = GetRiderDetailsResponse{}
	mi := &file_proto_rider_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRiderDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRiderDetailsResponse) ProtoMessage() {}

func (x *GetRiderDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rider_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRiderDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetRiderDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_rider_auth_proto_rawDescGZIP(), []int{6}
}

func (x *GetRiderDetailsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetRiderDetailsResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetRiderDetailsResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetRiderDetailsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Tokens struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,3,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"` // e.g., "Bearer"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tokens) Reset() {
	*x = Tokens{}
	mi := &file_proto_rider_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tokens) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tokens) ProtoMessage() {}

func (x *Tokens) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rider_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tokens.ProtoReflect.Descriptor instead.
func (*Tokens) Descriptor() ([]byte, []int) {
	return file_proto_rider_auth_proto_rawDescGZIP(), []int{7}
}

func (x *Tokens) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *Tokens) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *Tokens) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

var File_proto_rider_auth_proto protoreflect.FileDescriptor

const file_proto_rider_auth_proto_rawDesc = "" +
	"\n" +
	"\x16proto/rider_auth.proto\x12\n" +
	"rider_auth\"7\n" +
	"\x0fRegisterRequest\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.rider_auth.UserR\x04user\"\x86\x02\n" +
	"\x04User\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12\x1f\n" +
	"\vbirth_month\x18\x05 \x01(\tR\n" +
	"birthMonth\x12\x1d\n" +
	"\n" +
	"birth_year\x18\x06 \x01(\x03R\tbirthYear\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x0e\n" +
	"\x02id\x18\t \x01(\tR\x02id\"\xaa\x01\n" +
	"\fAuthResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x03R\x06status\x12$\n" +
	"\x04user\x18\x03 \x01(\v2\x10.rider_auth.UserR\x04user\x12(\n" +
	"\x05token\x18\x04 \x01(\v2\x12.rider_auth.TokensR\x05token\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xab\x01\n" +
	"\rLoginResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x03R\x06status\x12$\n" +
	"\x04user\x18\x03 \x01(\v2\x10.rider_auth.UserR\x04user\x12(\n" +
	"\x05token\x18\x04 \x01(\v2\x12.rider_auth.TokensR\x05token\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\"(\n" +
	"\x16GetRiderDetailsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8b\x01\n" +
	"\x17GetRiderDetailsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x03R\x06status\x12$\n" +
	"\x04user\x18\x03 \x01(\v2\x10.rider_auth.UserR\x04user\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"o\n" +
	"\x06Tokens\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x03 \x01(\tR\ttokenType2\xea\x01\n" +
	"\vAuthService\x12A\n" +
	"\bRegister\x12\x1b.rider_auth.RegisterRequest\x1a\x18.rider_auth.AuthResponse\x12<\n" +
	"\x05Login\x12\x18.rider_auth.LoginRequest\x1a\x19.rider_auth.LoginResponse\x12Z\n" +
	"\x0fGetRiderDetails\x12\".rider_auth.GetRiderDetailsRequest\x1a#.rider_auth.GetRiderDetailsResponseB\tZ\a.;protob\x06proto3"

var (
	file_proto_rider_auth_proto_rawDescOnce sync.Once
	file_proto_rider_auth_proto_rawDescData []byte
)

func file_proto_rider_auth_proto_rawDescGZIP() []byte {
	file_proto_rider_auth_proto_rawDescOnce.Do(func() {
		file_proto_rider_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rider_auth_proto_rawDesc), len(file_proto_rider_auth_proto_rawDesc)))
	})
	return file_proto_rider_auth_proto_rawDescData
}

var file_proto_rider_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_rider_auth_proto_goTypes = []any{
	(*RegisterRequest)(nil),         // 0: rider_auth.RegisterRequest
	(*User)(nil),                    // 1: rider_auth.User
	(*AuthResponse)(nil),            // 2: rider_auth.AuthResponse
	(*LoginRequest)(nil),            // 3: rider_auth.LoginRequest
	(*LoginResponse)(nil),           // 4: rider_auth.LoginResponse
	(*GetRiderDetailsRequest)(nil),  // 5: rider_auth.GetRiderDetailsRequest
	(*GetRiderDetailsResponse)(nil), // 6: rider_auth.GetRiderDetailsResponse
	(*Tokens)(nil),                  // 7: rider_auth.Tokens
}
var file_proto_rider_auth_proto_depIdxs = []int32{
	1, // 0: rider_auth.RegisterRequest.user:type_name -> rider_auth.User
	1, // 1: rider_auth.AuthResponse.user:type_name -> rider_auth.User
	7, // 2: rider_auth.AuthResponse.token:type_name -> rider_auth.Tokens
	1, // 3: rider_auth.LoginResponse.user:type_name -> rider_auth.User
	7, // 4: rider_auth.LoginResponse.token:type_name -> rider_auth.Tokens
	1, // 5: rider_auth.GetRiderDetailsResponse.user:type_name -> rider_auth.User
	0, // 6: rider_auth.AuthService.Register:input_type -> rider_auth.RegisterRequest
	3, // 7: rider_auth.AuthService.Login:input_type -> rider_auth.LoginRequest
	5, // 8: rider_auth.AuthService.GetRiderDetails:input_type -> rider_auth.GetRiderDetailsRequest
	2, // 9: rider_auth.AuthService.Register:output_type -> rider_auth.AuthResponse
	4, // 10: rider_auth.AuthService.Login:output_type -> rider_auth.LoginResponse
	6, // 11: rider_auth.AuthService.GetRiderDetails:output_type -> rider_auth.GetRiderDetailsResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_rider_auth_proto_init() }
func file_proto_rider_auth_proto_init() {
	if File_proto_rider_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rider_auth_proto_rawDesc), len(file_proto_rider_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rider_auth_proto_goTypes,
		DependencyIndexes: file_proto_rider_auth_proto_depIdxs,
		MessageInfos:      file_proto_rider_auth_proto_msgTypes,
	}.Build()
	File_proto_rider_auth_proto = out.File
	file_proto_rider_auth_proto_goTypes = nil
	file_proto_rider_auth_proto_depIdxs = nil
}
